dist: trusty
language: generic
install:
- python -m pip install --user pygments restructuredtext-lint
before_script:
- curl --version
script:
- ./c2-dl 'https://wiki.c2.com/?WorksForMe'
- shellcheck c2-dl
- restructuredtext-lint --encoding=UTF-8 README

# vim:ts=2 sts=2 sw=2 et
