name: CI
on:
- push
- pull_request
jobs:
  build:
    runs-on: ubuntu-18.04  # FIXME!
    steps:
    - uses: actions/checkout@v2
    - run: |
        python -m pip install --user pygments restructuredtext-lint
    - run: |
        curl --version
    - run: |
        ./c2-dl 'https://wiki.c2.com/?WorksForMe'
      env:
        OPENSSL_CONF: /dev/null
    - run: |
        shellcheck c2-dl
    - run: |
        restructuredtext-lint --encoding=UTF-8 README

# vim:ts=2 sts=2 sw=2 et
